apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: flasknode
  name: flask-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flasknode
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flasknode
    spec:
      containers:
      - image: private.icr.io/2021-fall-student-bd2119/k8s-infer:1
        imagePullPolicy: Always
        name: k8s-infer
        ports:
        - containerPort: 5000
          protocol: TCP
      imagePullSecrets:
      - name: all-icr-io
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30