apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-train
spec:
  template:
    metadata:
      labels:
        job-type: trainer
    spec:
      restartPolicy: Never
      containers:
      - image: icr.io/2021-fall-student-bd2119/k8s-train:1
        args: 
        imagePullPolicy: Always
        name: k8s-train
        # volumeMounts:
        #  - name:
      imagePullSecrets:
      - name: all-icr-io
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
               matchExpressions:
                  - key: "job-type"
                    operator: In
                    values:
                      - trainer
              topologyKey: "kubernetes.io/hostname"

      #volumes:
      #- name: 
      #  persistentVolumeClaim:
      #    claimName: